import { slugify } from "./slug";
import type { Painting } from "./types";

const RAW: Array<Omit<Painting, "collectionSlug">> = [
  {
    id: "stub-001",
    slug: "morning-lotus",
    title: "Morning Lotus",
    description:
      "Oil on canvas. A study of light filtering through lotus petals at dawn. Inspired by the ponds of Hue.",
    year: 2024,
    medium: "Oil on canvas",
    dimensions: "60 x 80 cm",
    imageDriveId: "stub",
    imageUrl: "https://placehold.co/1200x1500/e9d5b9/0a0a0a.png?text=Morning+Lotus",
    status: "available",
    featured: true,
    order: 1,
    collectionName: "Quiet Realism",
  },
  {
    id: "stub-002",
    slug: "river-evening",
    title: "River, Evening",
    description:
      "Watercolour on paper. The Perfume River as twilight settles over the old citadel.",
    year: 2023,
    medium: "Watercolour on paper",
    dimensions: "40 x 60 cm",
    imageDriveId: "stub",
    imageUrl: "https://placehold.co/1200x900/c8b6a6/0a0a0a.png?text=River%2C+Evening",
    status: "sold",
    featured: true,
    order: 2,
    collectionName: "Watercolour Sketches",
  },
  {
    id: "stub-003",
    slug: "still-life-with-mango",
    title: "Still Life with Mango",
    description:
      "Acrylic on canvas. A quiet table study, exploring colour balance and shadow.",
    year: 2024,
    medium: "Acrylic on canvas",
    dimensions: "50 x 50 cm",
    imageDriveId: "stub",
    imageUrl: "https://placehold.co/1200x1200/d9b48f/0a0a0a.png?text=Still+Life",
    status: "available",
    featured: true,
    order: 3,
    collectionName: "Quiet Realism",
  },
  {
    id: "stub-004",
    slug: "studio-window",
    title: "Studio Window",
    description: "Oil on canvas. Afternoon light in the studio.",
    year: 2024,
    medium: "Oil on canvas",
    dimensions: "70 x 90 cm",
    imageDriveId: "stub",
    imageUrl: "https://placehold.co/1200x1500/b8a890/0a0a0a.png?text=Studio+Window",
    status: "available",
    featured: false,
    order: 4,
    collectionName: "Quiet Realism",
  },
  {
    id: "stub-005",
    slug: "lotus-pond-at-noon",
    title: "Lotus Pond at Noon",
    description:
      "Watercolour on paper. Reflections rippling under the heat of midday.",
    year: 2024,
    medium: "Watercolour on paper",
    dimensions: "30 x 40 cm",
    imageDriveId: "stub",
    imageUrl: "https://placehold.co/1200x900/dcd0bf/0a0a0a.png?text=Lotus+Pond",
    status: "available",
    featured: false,
    order: 5,
    collectionName: "Watercolour Sketches",
  },
  {
    id: "stub-006",
    slug: "brass-doorway",
    title: "Brass Doorway",
    description:
      "Oil on linen. Detail study of a worn brass handle against deep wood grain.",
    year: 2023,
    medium: "Oil on linen",
    dimensions: "40 x 50 cm",
    imageDriveId: "stub",
    imageUrl: "https://placehold.co/1200x1500/a89478/faf7f6.png?text=Brass+Doorway",
    status: "available",
    featured: true,
    order: 6,
    collectionName: "Architectural Studies",
  },
  {
    id: "stub-007",
    slug: "stone-steps",
    title: "Stone Steps",
    description:
      "Oil on canvas. Worn limestone steps, late afternoon shadow falling across them.",
    year: 2023,
    medium: "Oil on canvas",
    dimensions: "55 x 70 cm",
    imageDriveId: "stub",
    imageUrl: "https://placehold.co/1200x1500/8d8a82/faf7f6.png?text=Stone+Steps",
    status: "reserved",
    featured: false,
    order: 7,
    collectionName: "Architectural Studies",
  },
  {
    id: "stub-008",
    slug: "window-into-stillness",
    title: "Window into Stillness",
    description:
      "Oil on canvas. A high arched window, its frame a study in vertical light.",
    year: 2025,
    medium: "Oil on canvas",
    dimensions: "80 x 110 cm",
    imageDriveId: "stub",
    imageUrl: "https://placehold.co/1200x1500/c1b8a8/0a0a0a.png?text=Window+Into+Stillness",
    status: "available",
    featured: true,
    order: 8,
    collectionName: "Architectural Studies",
  },
];

export const STUB_PAINTINGS: Painting[] = RAW.map((p) => ({
  ...p,
  collectionSlug: p.collectionName ? slugify(p.collectionName) : undefined,
}));
